apiVersion: v1
kind: Secret
metadata:
  namespace: ${NAMESPACE}
  name: aws-access-key-id
  labels:
    k8s-app: spot
type: Opaque
data:
  id: ${AWS_ACCESS_KEY_ID_ENCODED}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: ${NAMESPACE}
  name: aws-secret-access-key
  labels:
    k8s-app: spot
type: Opaque
data:
  key: ${AWS_SECRET_ACCESS_KEY_ENCODED}
