apiVersion: v1
kind: Secret
metadata:
  name: aws-access-key-id
  labels:
    {{- include "ec2-spot-scaling.labels" . | nindent 4 }}
    k8s-app: spot
type: Opaque
data:
  id: {{ .Values.aws.AWS_ACCESS_KEY_ID_ENCODED  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-access-key
  labels:
    {{- include "ec2-spot-scaling.labels" . | nindent 4 }}
    k8s-app: spot
type: Opaque
data:
  key: {{ .Values.aws.AWS_SECRET_ACCESS_KEY_ENCODED }}
